package domain

import "errors"

var (
	ErrMediaNotFound             = errors.New("media not found")
	ErrIndexerNotFound           = errors.New("indexer not found")
	ErrInvalidIndexerType        = errors.New("invalid indexer type")
	ErrDownloadClientNotFound    = errors.New("download client not found")
	ErrInvalidDownloadClientType = errors.New("invalid download client type")
	ErrPartNotFound              = errors.New("part not found")
	ErrQueueNotFound             = errors.New("queue item not found")
	ErrLibraryNotFound           = errors.New("library not found")
	ErrLibraryRequired           = errors.New("library is required")
	ErrInvalidMediaType          = errors.New("invalid media type")
	ErrEmptyName                 = errors.New("name cannot be empty")
	ErrEmptyPath                 = errors.New("path cannot be empty")
	ErrPathNotAbsolute           = errors.New("path must be absolute")
	ErrProviderNotSupported      = errors.New("provider not supported")
	ErrNoProviders               = errors.New("no media providers configured")
	ErrInvalidQuality            = errors.New("invalid quality")
	ErrProfileTypeNotAllowed     = errors.New("quality profiles are only allowed for movies and series")
	ErrProfileNotFound           = errors.New("quality profile not found")
	ErrProfileTypeMismatch       = errors.New("quality profile type does not match media type")
	ErrNoGrabber                 = errors.New("no grabber supports target")
	ErrTaskNotFound              = errors.New("task not found")
	ErrSourceNotFound            = errors.New("source not found")
	ErrInvalidSourceType         = errors.New("invalid source type")
	ErrNoToken                   = errors.New("source token is not configured")
	ErrProxyNotFound             = errors.New("proxy not found")
	ErrInvalidProxyType          = errors.New("invalid proxy type")
	ErrInvalidProxyEndpoint      = errors.New("invalid proxy endpoint")
	ErrUserNotFound              = errors.New("user not found")
	ErrDuplicateEmail            = errors.New("user with this email already exists")
	ErrInvalidCredentials        = errors.New("invalid email or password")
	ErrEmptyEmail                = errors.New("email cannot be empty")
	ErrPasswordRequired          = errors.New("password is required")
	ErrSessionNotFound           = errors.New("session not found")
	ErrInvalidRole               = errors.New("invalid role")
	ErrOIDCNotConfigured         = errors.New("oidc is not configured")
	ErrOIDCStateMismatch         = errors.New("oidc state mismatch")
	ErrLoginDisabled             = errors.New("local login is disabled")
	ErrRegistrationDisabled      = errors.New("registration is disabled")
	ErrPasswordTooShort          = errors.New("password must be at least 6 characters")
	ErrOIDCIdentityNotFound      = errors.New("oidc identity not found")
	ErrRequestNotFound            = errors.New("media request not found")
	ErrRequestNotPending          = errors.New("request is not pending")
	ErrRequestNotAuthorized       = errors.New("not authorized to modify this request")
	ErrDuplicateRequest           = errors.New("a pending or approved request for this media already exists")
	ErrMediaAlreadyExists         = errors.New("media already exists")
	ErrSettingNotFound            = errors.New("setting not found")
	ErrRequestsDisabled           = errors.New("media requests are disabled")
)
